version: '3'
#docker run -p 9000:9000
#--name minio1
# -v /mnt/data:/data
# -v /mnt/config:/root/.minio
# minio/minio server /data

services:
  minio:
    image: minio/minio
    volumes:
      - ./tmp/minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: ${STACKA_DB_PASSWORD}
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
